### ISSUE TITLE
CSS Issue

### ISSUE THREAD

**Issue by nilkanthdesai76** [coenttb/swift-html-to-pdf#5]
so basically i am creating a PDF file using a HTML which contains One image and it also contains some div with background color property.
But what happens here is that if i were to load the image in PDF the background colors of the Divs does not appear and in the same if i just remove the Image from the html then the backgroud colors are back again visible.
I was told by one of my fireld that it can be beacuse of using flex proprty but since i checked my HTML and i tried after removing flex as well but still the issue is happening.

**Comment by coenttb** [comment]
Hi @nilkanthdesai76, thank you for raising this issue. It would be helpful if you could provide a minimal reproduction of the issue so that I can investigate. Can you do this?

**Comment by nilkanthdesai76** [comment]
ok so basically when there is a backgroud color applied to any div but if that div also happens to have a img then the background color property is not rendering in the PDF but it is shown there if i load the same html in a webview

**Comment by coenttb** [comment]
It's not immediately clear to me why this would happen. I'll be able to check into it (hopefully) next week.

**Comment by nilkanthdesai76** [comment]
hey, i have found the solution so basically what's happening here is that after iOS 16 the swift language just ignores the background color property from css and to resolve the issue we need to add the below text in the stylesheet in the header style tag

<style>
     @media print {
         * {
                -webkit-print-color-adjust: exact !important;
            }
      }
</style>

**Comment by coenttb** [comment]
That’s great news! However, it seems that this library may not provide a solution, as it doesn’t directly handle CSS. Let me know if you have a different perspective on this.
